name: Bump Version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest tag
        id: latest_tag
        run: |
          tags=$(git tag)
          if [ -z "$tags" ]; then
            echo "No tags found, setting default tag to v1.0.0"
            echo "::set-output name=TAG::v1.0.0"
          else
            lastest_tag=$(git describe --tag $(git rev-list --tags --max-count=1))
            echo "Latest tag: $latest_tag"
            echo "::set-output name=TAG::$latest_tag"
          fi
      - name: Bump version
        id: bump_version
        run: |
          version=${{ steps.latest_tag.outputs.TAG }}
          echo "Curent version: $version"
          IFS='.' read -r major minor patch <<<"$version"
          new_version="$major.$minor.$new_patch"
          echo "New version: $new_version"
          git tag "$new_version"
          echo "::set-output name=NEW_TAG::$new_version"
      - name: Push new tag
        run: |
          new_tag=${{ steps.bump_version.output.NEW_TAG }}
          echo "Push new tag: $new_tag"
          git push origin $new_tag
