name: Bump Version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest tag
        id: latest_tag
        run: |
          tags=$(git tag)
          if [ -z "$tags" ]; then
            echo "TAG=v1.0.0" >> $GITHUB_OUTPUT
          else
            echo "TAG=$(git describe --tags $(git rev-list --tags --max-count=1))"
          fi

      - name: Bump version
        id: bump_version
        run: |
          version=${{ steps.latest_tag.outputs.TAG }}
          echo $version
          IFS='.' read -r major minor patch <<<"$version"
          new_version="$major.$minor.$((patch + 1))"
          echo "$new_version"
          git tag "$new_version"
          echo "NEW_TAG=$new_version" >> $GITHUB_OUTPUT

      - name: Push new tag
        run: git push origin ${{ steps.bump_version.outputs.NEW_TAG }}
