name: Bump Version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest tag
        id: latest_tag
        run: |
          latest_tag=$(curl -s -H "Authorization: token bumptag" \
                         "https://api.github.com/repos/gopichand.vattikuti@gmail.com/https://github.com/MrChandu55/TestPublic.git/tags" \
                         | jq -r '.[0].name')
          echo "::set-output name=TAG::$latest_tag"

          if [ -z "$tags" ]; then
            echo "No tags found, setting default tag to v1.0.0"
            default_tag="v1.0.0"
            echo "::set-output name=TAG::$default_tag"
          else
            latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
            echo "::set-output name=TAG::$latest_tag"
          fi
      
            - name: Bump version
              id: bump_version
              run: |
                version=${{ steps.latest_tag.outputs.TAG }}
                echo "Current version: $version"
                IFS='.' read -r major minor patch <<<"$version"
                new_patch=$((patch + 1))
                new_version="$major.$minor.$new_patch"
                echo "New version: $new_version"
                echo "::set-output name=NEW_TAG::$new_version"
      
            - name: Push new tag
              run: |
                if [ -n "${{ steps.latest_tag.outputs.TAG }}" ]; then
                new_tag=${{ steps.latest_tag.outputs.TAG }}
              else
                  new_tag=${{ steps.bump_version.outputs.NEW_TAG }}
            fi
            echo "Pushing new tag: $new_tag"
            git push origin "$new_tag"
